mongodb:
  host: 'localhost'
  port: 62345
  database_name: "vision_project"
  collection_name: "state_db"
vision-project:
  controllers:
    is_debug: False
    is_record:
      evaluation: "data_capture/is_record_evaluation"
      interaction: "data_capture/is_record_interaction"
      perseverance: "data_capture/is_record_perseverance"
    is_start_interaction: "vision_project/controllers/is_start_interaction"
    update_window_seconds: 5
    minutes_between_interactions: 1
    node_name_topic: "vision_project/controllers/current_node_name"
    scheduled_window_minutes: 15
  params:
    seconds_until_interaction_timeout: 300
    max_num_of_prompted_per_day: 2
    max_num_of_perseverance_readings: 5
  data:
    evaluation: '/root/evaluation'
    data_capture: '/root/upload'
