name: Continuous Integration

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Test Vision Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]

    steps:
      - name: Checkout vision-project
        uses: actions/checkout@v2
        with:
          path: ${{ github.workspace }}/vision-project
          submodules: true

      - name: Checkout mongodb-statedb
        uses: actions/checkout@v2
        with:
          repository: audrow/mongodb-statedb
          path: ${{ github.workspace }}/mongodb-statedb

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for mongodb-statedb
          run: |
            python -m pip install --upgrade pip==20.3.3
            pip install .
          working-directory: ${{ github.workspace }}/mongodb-statedb

      - name: Install dependencies for interaction-engine
        run: pip install .
        working-directory: ${{ github.workspace }}/vision-project/src/ros_vision_interaction/src/interaction-engine

      - name: Install dependencies for vision-project
        run: pip install .
        working-directory: ${{ github.workspace }}/vision-project/src/ros_vision_interaction/src/vision-interaction

      - name: Run tests
        run: pytest
        working-directory: ${{ github.workspace }}/vision-project/src/ros_vision_interaction/src/vision-interaction/tests
