name: Continuous Integration

on:
  push:
  schedule:
    - cron: '0 0 * * *'

defaults:
  working-directory: ./src/ros_vision_interaction/src/vision-interaction

jobs:
  build:
    name: Test Vision Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup the project and install dependencies
        run: |
          python -m pip install --upgrade pip==20.3.3
          pip install .
      - name: Run tests
        run: pytest
